// DO NOT EDIT THIS FILE EVER. It is just to register babel before running
// typescript files.

require("@babel/register")({
  extensions: [".js", ".jsx", ".ts", ".tsx"],

  // When running in node, the babel preset needs to be configured to transpile
  // modules to commonjs. It's default is to favour a webpack environment.
  presets: [["@origin-digital/babel-preset", { modules: "cjs" }]],
});
